// This file is automatically generated. Do not edit it directly.
// SECURITY: Environment validation and sanitization

export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Single validation check with proper error handling
if (!SUPABASE_URL) {
  throw new Error('Missing environment variable: VITE_SUPABASE_URL');
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing environment variable: VITE_SUPABASE_ANON_KEY');
}

// Validate URL format for security
if (!SUPABASE_URL.startsWith('https://')) {
  throw new Error('SUPABASE_URL must use HTTPS for security');
}

// Validate key format (basic check)
if (SUPABASE_PUBLISHABLE_KEY.length < 50) {
  throw new Error('VITE_SUPABASE_ANON_KEY appears to be malformed');
}

